- name: Install python3 & pip3
  package:
    name: "{{ item }}"
    state: present
  with_items:
   - python3
   - python3-pip

- name: Install Python SDK for docker
  pip:
    name: docker

- name: Run cadvisor in docker container
  become: true
  docker_container:
    name: "cadvisor"
    image: "gcr.io/google-containers/cadvisor:{{ version }}"
    state: started
    ports:
     - "{{ cadvisor_port }}:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"


- name: "Allow Cadvisor port with ufw : {{ cadvisor_port }}"
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ cadvisor_port }}"
